modLoader="javafml"
loaderVersion="[42,)"
license="ARR"

[[mods]]
modId="everpotion"
version="${file.jarVersion}"
displayName="EverPotion"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/everpotion"
description="Refillable potions"

[[dependencies.everpotion]]
    modId="kiwi"
    mandatory=true
    versionRange="[8, 9)"
    ordering="NONE"
    side="BOTH"

[[dependencies.everpotion]]
    modId="skillslots"
    mandatory=true
    versionRange="[1, 2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.everpotion]]
    modId="lychee"
    mandatory=false
    versionRange="[3.14,)"
    ordering="NONE"
    side="BOTH"

[modproperties.everpotion]
    catalogueItemIcon="everpotion:core"
