modLoader="javafml"
loaderVersion="[38,)"
license="MIT"

[[mods]]
modId="everpotion"
version="${file.jarVersion}"
displayName="EverPotion"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/everpotion"
description="Refillable potions"

[[dependencies.everpotion]]
    modId="kiwi"
    mandatory=true
    versionRange="[5, 6)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.everpotion]]
    modId="forge"
    mandatory=true
    versionRange="[38, )"
    ordering="BEFORE"
    side="BOTH"

[modproperties.everpotion]
    catalogueItemIcon="everpotion:core"
