modLoader="javafml"
loaderVersion="[34.1,)"
license="MIT"

[[mods]]
modId="everpotion"
version="${file.jarVersion}"
displayName="EverPotion"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/everpotion"
description=""

[[dependencies.everpotion]]
    modId="kiwi"
    mandatory=true
    versionRange="[3.4, 3.10)"
    ordering="BEFORE"
    side="BOTH"

[modproperties.everpotion]
    catalogueItemIcon="everpotion:core" #Support for Catalogue mod
