modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="everpotion"
version="${file.jarVersion}"
displayName="EverPotion"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/everpotion"
description="Refillable potions"

[[dependencies.everpotion]]
    modId="kiwi"
    mandatory=true
    versionRange="[6, 7)"
    ordering="NONE"
    side="BOTH"

[[dependencies.everpotion]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[modproperties.everpotion]
    catalogueItemIcon="everpotion:core"
